http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  alumnos:
    host: localhost
    paths: '/listar/alumnos'
  transaction:
    host: localhost
    paths: '/api/v2/transaction/List/:account_id'
  gestion:
    host: localhost
    paths: '/api/v2/listclients'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  alumnoService:
    url: 'http://integrationapi.tk:7000'
  transactionService:
    url: 'http://localhost:3000'
  gestionService:
    url: 'https://apigesbanc.herokuapp.com'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api 
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  listarAlumnos:
    apiEndpoints:
      - alumnos 
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: alumnoService 
              changeOrigin: true
  listTransaction:
    apiEndpoints:
      - transaction 
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: transactionService 
              changeOrigin: true   
  listGestion:
    apiEndpoints:
      - gestion 
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: gestionService 
              changeOrigin: true          
